### ISSUE TITLE
关于客户端加密解密的过程

### ISSUE THREAD

**Issue by think2011** [hangim/17wo#1]
你好，我抓包后发现登录和签到的发出的字段是类似这样的

```
loginType: PCmbVcp/ 9k=
platform:aeEgoMQ8b64=
```

据说是 `base64` 但是解密后发现依然是乱码，很是疑惑，如果可以的话，请告诉我吧，谢谢 ：）

**Comment by pdszhh** [comment]
是 DES

**Comment by think2011** [comment]
谢谢，那么对应的密钥应该是在客户端找得到吧？

**Comment by think2011** [comment]
我想应该会挺多需要了解的，非常感谢你，我自己去折腾了
